### ISSUE TITLE
Fine 0 potentialPos in getDepthBuffer()

### ISSUE THREAD

**Issue by yifenghuang** [xiaofeng94/renderdoc_for_gamedata#1]
I run the extract_depth_and_image_for_GTAV.py and set the python library directory and list_file directory. Then I run the script but in the getDepthBuffer() the length of potentialPos is 0.

I print all the drawcalls and here they are:
Array[FetchDrawcall]((<renderdoc.FetchDrawcall object at 0x000000000000002B [renderdoc.FetchDrawcall]>, <renderdoc.FetchDrawcall object at 0x000000000000002C [renderdoc.FetchDrawcall]>, <renderdoc.FetchDrawcall object at 0x000000000000002D [renderdoc.FetchDrawcall]>, <renderdoc.FetchDrawcall object at 0x000000000000002E [renderdoc.FetchDrawcall]>, <renderdoc.FetchDrawcall object at 0x000000000000002F 
.......

how could this happen?

and another question is the depth_list_file. is the directory inside the txt store the output depth image? or why this is a input list.

thank you!

**Comment by xiaofeng94** [comment]
potentialPos is to record indexes of FetchDrawcalls with name containing 'Targets + Depth)'. If len(potentialPos) = 0, check if the frame you captured has such a FetchDrawcall in Renderdoc GUI.

depth_list_file is only to record depth image paths in a txt file. And config['save_dir'] refers to the dir to save depth image.
